### ISSUE TITLE
Docker build not working with Apple Mx platforms

### ISSUE THREAD

**Issue by laveez** [Linkkijkl/linkki-web#118]
![image](https://github.com/Linkkijkl/linkki-web/assets/37067069/eb591e96-9e1a-4e32-bcc2-c56c87596c51)

Tested with 
2021 Apple M1 Max
macOS 14.4
Docker v4.10.1

**Comment by lurppa** [comment]
Can you test if #127 fixes this issue? Both Alpine Linux and its Hugo package have support for ARM so this should work on your platform. I have no access to Apple Mx devices so I can't test this myself.
