### ISSUE TITLE
Escapen jäsenedut ajantasalle

### ISSUE THREAD

**Issue by ikaros02** [Linkkijkl/linkki-web#151]
Uusi sopimus astuu voimaan 1.6.2024

**Comment by lurppa** [comment]
Fixed in #154

**Comment by zSanttu** [comment]
Sivuilla lukee nyt opiskelijabileissä olevat alennukset, eikä jäsenedut.

↓ Sivulla pitäisi siis lukea nämä ↓

Linkin jäsenedut 1.6.2024 alkaen:

- hanaolut 0,3l 4,20 €
- hanasiideri 0,3l 4,90 €
- hanalonkero 0,3l 4,90 €
- Linkki -drinkki 4,90 €

**Comment by zSanttu** [comment]
Korjattu https://github.com/Linkkijkl/linkki-web/pull/155
