### ISSUE TITLE
Information page for new students needed

### ISSUE THREAD

**Issue by ikaros02** [Linkkijkl/linkki-web#175]
Les autres associations d'étudiants ont des pages d'info pour les étudiants nouveaus, par exemple 
- Radikaali: http://www.radikaali.fi/fuksi-info/
- Algo: https://www.algojkl.com/fuksit

Je crois nous doivens avoir cette page aussi. Qu'est-ce que vous pensez?

**Comment by lurppa** [comment]
0/5 had to use a language model

> # We don't have an information page for new students
>
> The other student associations have information pages for new students, for example:
> - Radikaali: http://www.radikaali.fi/fuksi-info/
> - Algo: https://www.algojkl.com/fuksit
> 
> I think we should have this page too. What do you think?

**Comment by lurppa** [comment]
Great idea! Optima est tua sententia!

**Comment by 45spoons** [comment]
This would be amazing to have added! Since this is a time-sensitive page addition, all small nudges are important!

**Comment by ikaros02** [comment]
Myös "hae opiskelemaan" -sivu voisi olla hyödyllinen, joskin matalan prioriteetin tehtävä: https://www.parku.fi/hae-opiskelemaan/
