### ISSUE TITLE
Footer säännöt linkki rikki

### ISSUE THREAD

**Issue by LKKarjalainen** [Linkkijkl/linkki-web#226]
Pitäisi olla https://linkkijkl.fi/säännöt/

mutta on https://linkkijkl.fi/yhdistys/säännöt/

**Comment by tujokuus** [comment]
Footer linkin korjaus vaatii(ehkä?) muutoksia /public/säännöt/index.html tiedostoon, mutta public on .gitignore listassa 
```
.DS_Store
public/
.hugo_build.lock
resources/
```

**Comment by lurppa** [comment]
`public`-hakemisto on Hugon generoima "valmis" sivu. Tuo footteri on valitsemamme teeman tekosia, mutta sen tekijät olivat tehneet helpon tavan muokata sitä ja se löytyypi täältä: https://github.com/Linkkijkl/linkki-web/blob/3e9f7a616a2073cc94355056959e03ec624d98c1/hugo.toml#L362-L383 
Pakko kirjoittaa joku päivä näille projektin sijainneille vähän dokumentaatiota... mutta se päivä ei ole tänään :)
