### ISSUE TITLE
No margin for buttons

### ISSUE THREAD

**Issue by lurppa** [Linkkijkl/linkki-web#70]
Main page calendar subscription button gets placed right beside its containing elements border and looks awkward.
![image](https://github.com/Linkkijkl/linkki-web/assets/5105063/11f8d2e0-5758-4891-be0e-87f43e62d695)

**Comment by viljokass** [comment]
![Näyttökuva 2024-03-13 231257](https://github.com/Linkkijkl/linkki-web/assets/156933370/7f9f4a82-742b-4df7-8810-7890564d2572)
