### ISSUE TITLE
Calendar subscription button is in a weird place

### ISSUE THREAD

**Issue by viljokass** [Linkkijkl/linkki-web#98]
![Näyttökuva 2024-03-19 015620](https://github.com/Linkkijkl/linkki-web/assets/156933370/d9414b24-39cf-4887-9a26-81893aec7528)

Like this

**Comment by 45spoons** [comment]
![image](https://github.com/Linkkijkl/linkki-web/assets/73328090/eba1d65d-655e-421d-89b2-de63f24ee149)
I feel this is likely due to the button not being in its own bootstrap row
